# Generated by Django 3.0 on 2019-12-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeBoxProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(related_name='author_favorites', to='recipeBoxProject.RecipeItem'),
        ),
    ]
