# Generated by Django 2.2.6 on 2019-10-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeBoxProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='body',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='date',
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default='INSERT BIO', max_length=250),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='description',
            field=models.TextField(default='RECIPE DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='instructions',
            field=models.TextField(default='RECIPE INSTRUCTIONS'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='time',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='title',
            field=models.CharField(default='TITLE OF RECIPE', max_length=100),
        ),
    ]
