# Generated by Django 2.2.6 on 2019-11-01 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipeBoxProject', '0002_auto_20191028_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
